---
name: CI
on:
  - push
  - create
  - pull_request
jobs:
  deployment1:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
